chore: waitFor table to be created
Test fails with:
ResourceInUseException: Attempt to change a resource which is still in use: Table is being created: aws-js-integration-imtnejviovb
        at JsonRpcParser.Object.<anonymous>.exports.jsonErrorUnmarshaller [as parseServiceException] (/Users/trivikr/workspace/aws-sdk-js-v3/packages/json-error-unmarshaller/src/index.ts:51:35)
        at JsonRpcParser.<anonymous> (/Users/trivikr/workspace/aws-sdk-js-v3/packages/protocol-json-rpc/src/JsonRpcParser.ts:33:18)
        at step (/Users/trivikr/workspace/aws-sdk-js-v3/node_modules/tslib/tslib.js:136:27)
        at Object.next (/Users/trivikr/workspace/aws-sdk-js-v3/node_modules/tslib/tslib.js:117:57)
        at fulfilled (/Users/trivikr/workspace/aws-sdk-js-v3/node_modules/tslib/tslib.js:107:62)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)